import { readFile, mkdir, writeFile, cp, rm } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const out = new URL('dist/', root);
await rm(out, { recursive: true, force: true });
await mkdir(new URL('server/', out), { recursive: true });
await mkdir(new URL('.openai/', out), { recursive: true });
const html = await readFile(new URL('atlas/index.html', root), 'utf8');
const css = (await Promise.all(['atlas/style.css', 'shared/atlas-palette.css', 'shared/atlas-neumorphism.css', 'shared/atlas-appearance.css'].map(path => readFile(new URL(path, root), 'utf8')))).join('\n');
const js = await readFile(new URL('atlas/app.js', root), 'utf8');
const theme = await readFile(new URL('shared/atlas-theme.js', root), 'utf8');
const model = await readFile(new URL('atlas/model.mjs', root), 'utf8');
const heraldModel = await readFile(new URL('atlas/herald.mjs', root), 'utf8');
const heraldUI = await readFile(new URL('atlas/herald-ui.mjs', root), 'utf8');
const communicationModel = await readFile(new URL('atlas/communication.mjs', root), 'utf8');
const communicationUI = await readFile(new URL('atlas/communication-ui.mjs', root), 'utf8');
const ledgerModel = await readFile(new URL('atlas/ledger.mjs', root), 'utf8');
const reflectionUI = await readFile(new URL('atlas/reflection-ui.mjs', root), 'utf8');
const editionUI = await readFile(new URL('atlas/edition-refresh-ui.mjs', root), 'utf8');
const ledgerUI = await readFile(new URL('atlas/ledger-ui.mjs', root), 'utf8');
await writeFile(new URL('server/assets.mjs', out), `export const html=${JSON.stringify(html)};\nexport const css=${JSON.stringify(css)};\nexport const js=${JSON.stringify(js)};\nexport const theme=${JSON.stringify(theme)};\nexport const model=${JSON.stringify(model)};\nexport const ledgerModel=${JSON.stringify(ledgerModel)};\nexport const ledgerUI=${JSON.stringify(ledgerUI)};\nexport const editionUI=${JSON.stringify(editionUI)};\nexport const reflectionUI=${JSON.stringify(reflectionUI)};\nexport const communicationModel=${JSON.stringify(communicationModel)};\nexport const communicationUI=${JSON.stringify(communicationUI)};\nexport const heraldModel=${JSON.stringify(heraldModel)};\nexport const heraldUI=${JSON.stringify(heraldUI)};\n`);
await cp(new URL('atlas/worker.mjs', root), new URL('server/index.js', out));
// Sites registers Worker modules from the server directory. Flatten this shared
// dependency into that directory while keeping a single source for both apps.
const editions = await readFile(new URL('atlas/courier-editions.mjs', root), 'utf8');
if(!editions.includes("from '../shared/courier-lessons.mjs'")) throw Error('Courier module import changed; update its staging path.');
await writeFile(new URL('server/courier-editions.mjs', out), editions.replace("from '../shared/courier-lessons.mjs'", "from './courier-lessons.mjs'"));
await cp(new URL('shared/courier-lessons.mjs', root), new URL('server/courier-lessons.mjs', out));
await cp(new URL('atlas/model.mjs', root), new URL('server/model.mjs', out));
await cp(new URL('atlas/herald.mjs', root), new URL('server/herald.mjs', out));
await cp(new URL('atlas/communication.mjs', root), new URL('server/communication.mjs', out));
await cp(new URL('atlas/ledger.mjs', root), new URL('server/ledger.mjs', out));
await cp(new URL('atlas/recovery.mjs', root), new URL('server/recovery.mjs', out));
await cp(new URL('.openai/hosting.json', root), new URL('.openai/hosting.json', out));
await cp(new URL('drizzle/', root), new URL('.openai/drizzle/', out), { recursive: true });
console.log('Atlas Worker and schema migrations prepared.');
